// Generated by CoffeeScript 1.9.2
(function() {
  var merge,
    slice = [].slice;

  merge = function() {
    var data, out;
    data = 1 <= arguments.length ? slice.call(arguments, 0) : [];

    /*
    Merge objects using native d3.
     */
    out = {};
    data.forEach(function(d) {
      return d3.entries(d).forEach(function(d) {
        return out[d.key] = d.value;
      });
    });
    return out;
  };

}).call(this);

//# sourceMappingURL=d3.merge.js.map
